# This file is covered by the LICENSE file in the root of this project.
anovox_labels:
  0: "unlabeled"
  1: "road"
  2: "sidewalk"
  3: "building"
  4: "wall"
  5: "fence"
  6: "pole"
  7: "traffic-light"
  8: "traffic-sign"
  9: "vegetation"
  10: "terrain"
  11: "sky"
  12: "pedestrian"
  13: "rider"
  14: "Car"
  15: "truck"
  16: "bus"
  17: "train"
  18: "motorcycle"
  19: "bicycle"
  20: "static"
  21: "dynamic"
  22: "other"
  23: "water"
  24: "road-line"
  25: "ground"
  26: "bridge"
  27: "rail-track"
  28: "guard-rail"
  29: "home"
  30: "animal"
  31: "nature"
  33: "anomaly"
  34: "anomaly"

# color_map:
#   0: [0, 0, 0]
#   1: [128, 64, 128]
#   2: [244, 35, 232]
#   3: [70, 70, 70]
#   4: [102, 102, 156]
#   5: [190, 153, 153]
#   6: [153, 153, 153]
#   7: [250, 170, 30]
#   8: [220, 220, 0]
#   9: [107, 142, 35]
#   10: [152, 251, 152]
#   11: [70, 130, 180]
#   12: [220, 20, 60]
#   13: [255, 0, 0]
#   14: [0, 0, 142]
#   15: [0, 0, 70]
#   16: [0, 60, 100]
#   17: [0, 80, 100]
#   18: [0, 0, 230]
#   19: [119, 11, 32]
#   20: [110, 190, 160]
#   21: [170, 120, 50]
#   22: [55, 90, 80]
#   23: [45, 60, 150]
#   24: [157, 234, 50]
#   25: [81, 0, 81]
#   26: [150, 100, 100]
#   27: [230, 150, 140]
#   28: [180, 165, 180]
#   29: [250, 128, 114]
#   30: [255, 36, 0]
#   31: [224, 17, 95]
#   32: [184, 15, 10]
#   33: [245, 0, 0]
#   34: [245, 0, 0]

color_map:
  - [0, 0, 0]
  - [128, 64, 128]
  - [244, 35, 232]
  - [70, 70, 70]
  - [102, 102, 156]
  - [190, 153, 153]
  - [153, 153, 153]
  - [250, 170, 30]
  - [220, 220, 0]
  - [107, 142, 35]
  - [152, 251, 152]
  - [70, 130, 180]
  - [220, 20, 60]
  - [255, 0, 0]
  - [0, 0, 142]
  - [0, 0, 70]
  - [0, 60, 100]
  - [0, 80, 100]
  - [0, 0, 230]
  - [119, 11, 32]
  - [110, 190, 160]
  - [170, 120, 50]
  - [55, 90, 80]
  - [45, 60, 150]
  - [157, 234, 50]
  - [81, 0, 81]
  - [150, 100, 100]
  - [230, 150, 140]
  - [180, 165, 180]
  - [250, 128, 114]
  - [255, 36, 0]
  - [224, 17, 95]
  - [184, 15, 10]
  - [245, 0, 0]
  - [245, 0, 0]

to_SemKITTI:
  - 0
  - 40
  - 48
  - 50
  - 52
  - 51
  - 80
  - 99
  - 81
  - 70
  - 72
  - 0
  - 30
  - 32
  - 10
  - 18
  - 13
  - 20
  - 15
  - 31
  - 99
  - 99
  - 99
  - 0
  - 60
  - 49
  - 52
  - 16
  - 16
  - 50
  - 99
  - 0
  - 0
  - 1
  - 1

labels: # from semantic kitti
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"

learning_map:
  0 : 0     # "unlabeled"
  1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 2     # "bicycle"
  13: 5     # "bus" mapped to "other-vehicle" --------------------------mapped
  15: 3     # "motorcycle"
  16: 5     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 4     # "truck"
  20: 5     # "other-vehicle"
  30: 6     # "person"
  31: 7     # "bicyclist"
  32: 8     # "motorcyclist"
  40: 9     # "road"
  44: 10    # "parking"
  48: 11    # "sidewalk"
  49: 12    # "other-ground"
  50: 13    # "building"
  51: 14    # "fence"
  52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  60: 9     # "lane-marking" to "road" ---------------------------------mapped
  70: 15    # "vegetation"
  71: 16    # "trunk"
  72: 17    # "terrain"
  80: 18    # "pole"
  81: 19    # "traffic-sign"
  99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 7    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 6    # "moving-person" to "person" ------------------------------mapped
  255: 8    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 5    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 5    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  258: 4    # "moving-truck" to "truck" --------------------------------mapped
  259: 5    # "moving-other"-vehicle to "other-vehicle" ----------------mapped

  # learning_map:
  #   0 : 0     # "unlabeled"
  #   1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  #   10: 1     # "car"
  #   11: 2     # "bicycle"
  #   13: 5     # "bus" mapped to "other-vehicle" --------------------------mapped
  #   15: 3     # "motorcycle"
  #   16: 5     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  #   18: 4     # "truck"
  #   20: 5     # "other-vehicle"
  #   30: 6     # "person"
  #   31: 7     # "bicyclist"
  #   32: 8     # "motorcyclist"
  #   40: 9     # "road"
  #   44: 10    # "parking"
  #   48: 11    # "sidewalk"
  #   49: 12    # "other-ground"
  #   50: 13    # "building"
  #   51: 14    # "fence"
  #   52: 0     # "other-structure" mapped to "unlabeled" ------------------mapped
  #   60: 9     # "lane-marking" to "road" ---------------------------------mapped
  #   70: 15    # "vegetation"
  #   71: 16    # "trunk"
  #   72: 17    # "terrain"
  #   80: 18    # "pole"
  #   81: 19    # "traffic-sign"
  #   99: 0     # "other-object" to "unlabeled" ----------------------------mapped
  #   252: 1    # "moving-car" to "car" ------------------------------------mapped
  #   253: 7    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  #   254: 6    # "moving-person" to "person" ------------------------------mapped
  #   255: 8    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  #   256: 5    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  #   257: 5    # "moving-bus" mapped to "other-vehicle" -------------------mapped
  #   258: 4    # "moving-truck" to "truck" --------------------------------mapped
  #   259: 5    # "moving-other"-vehicle to "other-vehicle" ----------------mapped